# Generated by Django 3.1.5 on 2021-02-02 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_no', models.AutoField(primary_key=True, serialize=False)),
                ('artist_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='음악 장르를 입력하세요', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('list_no', models.AutoField(primary_key=True, serialize=False)),
                ('list_name', models.CharField(default='my playlist', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('music_no', models.AutoField(primary_key=True, serialize=False)),
                ('music_name', models.CharField(max_length=20)),
                ('music_composer', models.CharField(max_length=15)),
                ('music_lyricsist', models.CharField(max_length=15)),
                ('music_lyrics', models.TextField()),
                ('music_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist', to='blog.artist')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='artist_category',
            field=models.ManyToManyField(help_text='음악 장르를 설정하세요', to='blog.Category'),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_no', models.AutoField(primary_key=True, serialize=False)),
                ('album_name', models.CharField(default='', max_length=15)),
                ('album_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('album_decribe', models.TextField(null=True)),
                ('album_artist_no', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='album_artist', to='blog.artist')),
            ],
        ),
    ]
