# Generated by Django 3.1.5 on 2021-02-04 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='list_name',
        ),
        migrations.AddField(
            model_name='music',
            name='music_file',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='playlist',
            name='music_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playlist_music_no', to='blog.music'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='user_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playlist_user_no', to=settings.AUTH_USER_MODEL),
        ),
    ]
