# Generated by Django 3.1.5 on 2021-02-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210204_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_music',
            field=models.ManyToManyField(to='blog.Music'),
        ),
    ]
