# Generated by Django 3.1.5 on 2021-02-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_album_album_music'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='music_no',
        ),
        migrations.AddField(
            model_name='playlist',
            name='music_no',
            field=models.ManyToManyField(to='blog.Music'),
        ),
    ]
