# Generated by Django 3.1.5 on 2021-02-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210204_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='music_no',
            field=models.ManyToManyField(related_name='playlist_music_no', to='blog.Music'),
        ),
    ]
